### ISSUE TITLE
unable to add accessory failed with osstatus code -6700

### ISSUE THREAD

**Issue by cirrusflyer** [paullj1/TreatLife-HomeKit#2]
Successfully installed the DS01C firmware on my switch.  Added to wifi successfully.  Now when adding to Homekit, I see it fine but after entering the Homekit code, I get this error:   "unable to add accessory failed with OSStatus code -6700"

*Update: turns out I have a DS01.  I updated to the DS02S firmware (gz version), and now the switch works perfectly.

**Comment by paullj1** [comment]
Interesting, I don’t think I’ve run into the DS01, but glad the DS02S did it for you!  Is the DS01 a three way dimmer? I’d be happy to document it if I had some more details about the device!

**Comment by paullj1** [comment]
Actually, that update probably failed (because the gz versions are only for upgrading from Tasmota) and then the reboot, and subsequent attempt to pair succeeded. If you look at the device details in the home app, what does it say the model number is?

**Comment by cirrusflyer** [comment]
The model is the DS01, but I think there's also a newer DS01C.  When I tried that firmware it produced the error.  And I misspoke earlier - I didn't use the gz file, but rather just the DS02S bin file.  And of course that works great now.  The DS01 is a touch dimmer switch that's identical to the DS01C as far as I can tell.

**Comment by paullj1** [comment]
Okay, that makes more sense!  I’ll update the docs to reflect that, and make another release binary (so the model number is accurately reflected in the Home app). Thanks!!

**Comment by paullj1** [comment]
Hey, so sorry it's taken so long, but looking at the code now, and there's no difference between the DS02S and DS01C code (other than how it reports the model number in the Home app).  I was expecting to see a different serial baud rate since Treatlife has been updating that on newer devices, but in this case it's the same.  Perhaps there was something wrong with the initial attempt?  Closing the issue for now, but please re-open if you think I missed something!
